name: root
channels:
  - conda-forge
dependencies:
  - python=3.6
  - jupyterlab
  - pandas==0.23.0
  - libgdal==2.2.4
  - fiona==1.7.11
  - geopandas==0.3.0
  - requests==2.18.4
  - scipy==0.19.0
  - scikit-learn==0.19.0
  - matplotlib==2.1.1
  - tqdm==4.19.2
  - pip
  - pip:
    - altair==2.1.0